//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GalleryModel", "FK_Categories_Users", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineGallery.User), "Categories", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineGallery.Category))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GalleryModel", "FK_Images_Category", "Categories", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineGallery.Category), "Images", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineGallery.Image))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GalleryModel", "FK_ImageComments_Image", "Images", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineGallery.Image), "ImageComments", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineGallery.ImageComment))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GalleryModel", "FK_ImageComments_User", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineGallery.User), "ImageComments", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineGallery.ImageComment))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GalleryModel", "FK_ImageRatings_Image", "Images", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineGallery.Image), "ImageRatings", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineGallery.ImageRating))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GalleryModel", "FK_ImageRatings_User", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineGallery.User), "ImageRatings", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineGallery.ImageRating))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GalleryModel", "FK_Images_User", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineGallery.User), "Images", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineGallery.Image))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GalleryModel", "FK_ImageVisits_Image", "Images", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineGallery.Image), "ImageVisits", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineGallery.ImageVisit))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GalleryModel", "FK_ImageVisits_User", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineGallery.User), "ImageVisits", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineGallery.ImageVisit))]

// Original file name:
// Generation date: 13.3.2010 г. 16:47 ч.
namespace OnlineGallery
{
    
    /// <summary>
    /// There are no comments for Entities in the schema.
    /// </summary>
    public partial class Entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : 
                base("name=Entities", "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : 
                base(connectionString, "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "Entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for CategorySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Category> CategorySet
        {
            get
            {
                if ((this._CategorySet == null))
                {
                    this._CategorySet = base.CreateQuery<Category>("[CategorySet]");
                }
                return this._CategorySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Category> _CategorySet;
        /// <summary>
        /// There are no comments for ImageCommentSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ImageComment> ImageCommentSet
        {
            get
            {
                if ((this._ImageCommentSet == null))
                {
                    this._ImageCommentSet = base.CreateQuery<ImageComment>("[ImageCommentSet]");
                }
                return this._ImageCommentSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ImageComment> _ImageCommentSet;
        /// <summary>
        /// There are no comments for ImageRatingSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ImageRating> ImageRatingSet
        {
            get
            {
                if ((this._ImageRatingSet == null))
                {
                    this._ImageRatingSet = base.CreateQuery<ImageRating>("[ImageRatingSet]");
                }
                return this._ImageRatingSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ImageRating> _ImageRatingSet;
        /// <summary>
        /// There are no comments for ImageSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Image> ImageSet
        {
            get
            {
                if ((this._ImageSet == null))
                {
                    this._ImageSet = base.CreateQuery<Image>("[ImageSet]");
                }
                return this._ImageSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Image> _ImageSet;
        /// <summary>
        /// There are no comments for ImageVisitSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ImageVisit> ImageVisitSet
        {
            get
            {
                if ((this._ImageVisitSet == null))
                {
                    this._ImageVisitSet = base.CreateQuery<ImageVisit>("[ImageVisitSet]");
                }
                return this._ImageVisitSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ImageVisit> _ImageVisitSet;
        /// <summary>
        /// There are no comments for UserSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<User> UserSet
        {
            get
            {
                if ((this._UserSet == null))
                {
                    this._UserSet = base.CreateQuery<User>("[UserSet]");
                }
                return this._UserSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<User> _UserSet;
        /// <summary>
        /// There are no comments for CategorySet in the schema.
        /// </summary>
        public void AddToCategorySet(Category category)
        {
            base.AddObject("CategorySet", category);
        }
        /// <summary>
        /// There are no comments for ImageCommentSet in the schema.
        /// </summary>
        public void AddToImageCommentSet(ImageComment imageComment)
        {
            base.AddObject("ImageCommentSet", imageComment);
        }
        /// <summary>
        /// There are no comments for ImageRatingSet in the schema.
        /// </summary>
        public void AddToImageRatingSet(ImageRating imageRating)
        {
            base.AddObject("ImageRatingSet", imageRating);
        }
        /// <summary>
        /// There are no comments for ImageSet in the schema.
        /// </summary>
        public void AddToImageSet(Image image)
        {
            base.AddObject("ImageSet", image);
        }
        /// <summary>
        /// There are no comments for ImageVisitSet in the schema.
        /// </summary>
        public void AddToImageVisitSet(ImageVisit imageVisit)
        {
            base.AddObject("ImageVisitSet", imageVisit);
        }
        /// <summary>
        /// There are no comments for UserSet in the schema.
        /// </summary>
        public void AddToUserSet(User user)
        {
            base.AddObject("UserSet", user);
        }
    }
    /// <summary>
    /// There are no comments for GalleryModel.Category in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GalleryModel", Name="Category")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Category : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="isPrimary">Initial value of IsPrimary.</param>
        public static Category CreateCategory(long id, bool isPrimary)
        {
            Category category = new Category();
            category.ID = id;
            category.IsPrimary = isPrimary;
            return category;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property IsPrimary in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrimary
        {
            get
            {
                return this._IsPrimary;
            }
            set
            {
                this.OnIsPrimaryChanging(value);
                this.ReportPropertyChanging("IsPrimary");
                this._IsPrimary = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsPrimary");
                this.OnIsPrimaryChanged();
            }
        }
        private bool _IsPrimary;
        partial void OnIsPrimaryChanging(bool value);
        partial void OnIsPrimaryChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_Categories_Users", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_Categories_Users", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_Categories_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_Categories_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("GalleryModel.FK_Categories_Users", "Users", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Images in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_Images_Category", "Images")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Image> Images
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Image>("GalleryModel.FK_Images_Category", "Images");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Image>("GalleryModel.FK_Images_Category", "Images", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GalleryModel.ImageComment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GalleryModel", Name="ImageComment")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ImageComment : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ImageComment object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="dateWritten">Initial value of dateWritten.</param>
        /// <param name="description">Initial value of description.</param>
        public static ImageComment CreateImageComment(long id, global::System.DateTime dateWritten, string description)
        {
            ImageComment imageComment = new ImageComment();
            imageComment.ID = id;
            imageComment.dateWritten = dateWritten;
            imageComment.description = description;
            return imageComment;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property dateWritten in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime dateWritten
        {
            get
            {
                return this._dateWritten;
            }
            set
            {
                this.OndateWrittenChanging(value);
                this.ReportPropertyChanging("dateWritten");
                this._dateWritten = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dateWritten");
                this.OndateWrittenChanged();
            }
        }
        private global::System.DateTime _dateWritten;
        partial void OndateWrittenChanging(global::System.DateTime value);
        partial void OndateWrittenChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Image in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_ImageComments_Image", "Images")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Image Image
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Image>("GalleryModel.FK_ImageComments_Image", "Images").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Image>("GalleryModel.FK_ImageComments_Image", "Images").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Image in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Image> ImageReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Image>("GalleryModel.FK_ImageComments_Image", "Images");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Image>("GalleryModel.FK_ImageComments_Image", "Images", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_ImageComments_User", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_ImageComments_User", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_ImageComments_User", "Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_ImageComments_User", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("GalleryModel.FK_ImageComments_User", "Users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GalleryModel.ImageRating in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GalleryModel", Name="ImageRating")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ImageRating : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ImageRating object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="rating">Initial value of rating.</param>
        public static ImageRating CreateImageRating(long id, int rating)
        {
            ImageRating imageRating = new ImageRating();
            imageRating.ID = id;
            imageRating.rating = rating;
            return imageRating;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property rating in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int rating
        {
            get
            {
                return this._rating;
            }
            set
            {
                this.OnratingChanging(value);
                this.ReportPropertyChanging("rating");
                this._rating = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("rating");
                this.OnratingChanged();
            }
        }
        private int _rating;
        partial void OnratingChanging(int value);
        partial void OnratingChanged();
        /// <summary>
        /// There are no comments for Image in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_ImageRatings_Image", "Images")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Image Image
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Image>("GalleryModel.FK_ImageRatings_Image", "Images").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Image>("GalleryModel.FK_ImageRatings_Image", "Images").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Image in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Image> ImageReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Image>("GalleryModel.FK_ImageRatings_Image", "Images");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Image>("GalleryModel.FK_ImageRatings_Image", "Images", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_ImageRatings_User", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_ImageRatings_User", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_ImageRatings_User", "Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_ImageRatings_User", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("GalleryModel.FK_ImageRatings_User", "Users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GalleryModel.Image in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GalleryModel", Name="Image")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Image : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Image object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="image1">Initial value of image.</param>
        /// <param name="dateUploaded">Initial value of dateUploaded.</param>
        /// <param name="liked">Initial value of liked.</param>
        /// <param name="disliked">Initial value of disliked.</param>
        /// <param name="visits">Initial value of visits.</param>
        /// <param name="commens">Initial value of commens.</param>
        public static Image CreateImage(long id, byte[] image1, global::System.DateTime dateUploaded, long liked, long disliked, long visits, long commens)
        {
            Image image = new Image();
            image.ID = id;
            image.image = image1;
            image.dateUploaded = dateUploaded;
            image.liked = liked;
            image.disliked = disliked;
            image.visits = visits;
            image.commens = commens;
            return image;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property image in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] image
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._image);
            }
            set
            {
                this.OnimageChanging(value);
                this.ReportPropertyChanging("image");
                this._image = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("image");
                this.OnimageChanged();
            }
        }
        private byte[] _image;
        partial void OnimageChanging(byte[] value);
        partial void OnimageChanged();
        /// <summary>
        /// There are no comments for Property dateUploaded in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime dateUploaded
        {
            get
            {
                return this._dateUploaded;
            }
            set
            {
                this.OndateUploadedChanging(value);
                this.ReportPropertyChanging("dateUploaded");
                this._dateUploaded = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dateUploaded");
                this.OndateUploadedChanged();
            }
        }
        private global::System.DateTime _dateUploaded;
        partial void OndateUploadedChanging(global::System.DateTime value);
        partial void OndateUploadedChanged();
        /// <summary>
        /// There are no comments for Property liked in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long liked
        {
            get
            {
                return this._liked;
            }
            set
            {
                this.OnlikedChanging(value);
                this.ReportPropertyChanging("liked");
                this._liked = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("liked");
                this.OnlikedChanged();
            }
        }
        private long _liked;
        partial void OnlikedChanging(long value);
        partial void OnlikedChanged();
        /// <summary>
        /// There are no comments for Property disliked in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long disliked
        {
            get
            {
                return this._disliked;
            }
            set
            {
                this.OndislikedChanging(value);
                this.ReportPropertyChanging("disliked");
                this._disliked = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("disliked");
                this.OndislikedChanged();
            }
        }
        private long _disliked;
        partial void OndislikedChanging(long value);
        partial void OndislikedChanged();
        /// <summary>
        /// There are no comments for Property visits in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long visits
        {
            get
            {
                return this._visits;
            }
            set
            {
                this.OnvisitsChanging(value);
                this.ReportPropertyChanging("visits");
                this._visits = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("visits");
                this.OnvisitsChanged();
            }
        }
        private long _visits;
        partial void OnvisitsChanging(long value);
        partial void OnvisitsChanged();
        /// <summary>
        /// There are no comments for Property commens in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long commens
        {
            get
            {
                return this._commens;
            }
            set
            {
                this.OncommensChanging(value);
                this.ReportPropertyChanging("commens");
                this._commens = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("commens");
                this.OncommensChanged();
            }
        }
        private long _commens;
        partial void OncommensChanging(long value);
        partial void OncommensChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property thumbnail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] thumbnail
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._thumbnail);
            }
            set
            {
                this.OnthumbnailChanging(value);
                this.ReportPropertyChanging("thumbnail");
                this._thumbnail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("thumbnail");
                this.OnthumbnailChanged();
            }
        }
        private byte[] _thumbnail;
        partial void OnthumbnailChanging(byte[] value);
        partial void OnthumbnailChanged();
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_Images_Category", "Categories")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Category Category
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("GalleryModel.FK_Images_Category", "Categories").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("GalleryModel.FK_Images_Category", "Categories").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Category> CategoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("GalleryModel.FK_Images_Category", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Category>("GalleryModel.FK_Images_Category", "Categories", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ImageComments in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_ImageComments_Image", "ImageComments")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ImageComment> ImageComments
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ImageComment>("GalleryModel.FK_ImageComments_Image", "ImageComments");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ImageComment>("GalleryModel.FK_ImageComments_Image", "ImageComments", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ImageRatings in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_ImageRatings_Image", "ImageRatings")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ImageRating> ImageRatings
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ImageRating>("GalleryModel.FK_ImageRatings_Image", "ImageRatings");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ImageRating>("GalleryModel.FK_ImageRatings_Image", "ImageRatings", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_Images_User", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_Images_User", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_Images_User", "Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_Images_User", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("GalleryModel.FK_Images_User", "Users", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ImageVisits in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_ImageVisits_Image", "ImageVisits")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ImageVisit> ImageVisits
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ImageVisit>("GalleryModel.FK_ImageVisits_Image", "ImageVisits");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ImageVisit>("GalleryModel.FK_ImageVisits_Image", "ImageVisits", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GalleryModel.ImageVisit in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GalleryModel", Name="ImageVisit")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ImageVisit : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ImageVisit object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static ImageVisit CreateImageVisit(long id)
        {
            ImageVisit imageVisit = new ImageVisit();
            imageVisit.ID = id;
            return imageVisit;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Image in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_ImageVisits_Image", "Images")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Image Image
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Image>("GalleryModel.FK_ImageVisits_Image", "Images").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Image>("GalleryModel.FK_ImageVisits_Image", "Images").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Image in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Image> ImageReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Image>("GalleryModel.FK_ImageVisits_Image", "Images");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Image>("GalleryModel.FK_ImageVisits_Image", "Images", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_ImageVisits_User", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_ImageVisits_User", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_ImageVisits_User", "Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("GalleryModel.FK_ImageVisits_User", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("GalleryModel.FK_ImageVisits_User", "Users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GalleryModel.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GalleryModel", Name="User")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="username">Initial value of username.</param>
        /// <param name="password">Initial value of password.</param>
        /// <param name="dateRegistered">Initial value of dateRegistered.</param>
        public static User CreateUser(long id, string username, string password, global::System.DateTime dateRegistered)
        {
            User user = new User();
            user.ID = id;
            user.username = username;
            user.password = password;
            user.dateRegistered = dateRegistered;
            return user;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property username in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this._username;
            }
            set
            {
                this.OnusernameChanging(value);
                this.ReportPropertyChanging("username");
                this._username = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("username");
                this.OnusernameChanged();
            }
        }
        private string _username;
        partial void OnusernameChanging(string value);
        partial void OnusernameChanged();
        /// <summary>
        /// There are no comments for Property password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this._password;
            }
            set
            {
                this.OnpasswordChanging(value);
                this.ReportPropertyChanging("password");
                this._password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("password");
                this.OnpasswordChanged();
            }
        }
        private string _password;
        partial void OnpasswordChanging(string value);
        partial void OnpasswordChanged();
        /// <summary>
        /// There are no comments for Property dateRegistered in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime dateRegistered
        {
            get
            {
                return this._dateRegistered;
            }
            set
            {
                this.OndateRegisteredChanging(value);
                this.ReportPropertyChanging("dateRegistered");
                this._dateRegistered = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dateRegistered");
                this.OndateRegisteredChanged();
            }
        }
        private global::System.DateTime _dateRegistered;
        partial void OndateRegisteredChanging(global::System.DateTime value);
        partial void OndateRegisteredChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property city in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string city
        {
            get
            {
                return this._city;
            }
            set
            {
                this.OncityChanging(value);
                this.ReportPropertyChanging("city");
                this._city = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("city");
                this.OncityChanged();
            }
        }
        private string _city;
        partial void OncityChanging(string value);
        partial void OncityChanged();
        /// <summary>
        /// There are no comments for Property birthdate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> birthdate
        {
            get
            {
                return this._birthdate;
            }
            set
            {
                this.OnbirthdateChanging(value);
                this.ReportPropertyChanging("birthdate");
                this._birthdate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("birthdate");
                this.OnbirthdateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _birthdate;
        partial void OnbirthdateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnbirthdateChanged();
        /// <summary>
        /// There are no comments for Property email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this._email;
            }
            set
            {
                this.OnemailChanging(value);
                this.ReportPropertyChanging("email");
                this._email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("email");
                this.OnemailChanged();
            }
        }
        private string _email;
        partial void OnemailChanging(string value);
        partial void OnemailChanged();
        /// <summary>
        /// There are no comments for Property moreInfo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string moreInfo
        {
            get
            {
                return this._moreInfo;
            }
            set
            {
                this.OnmoreInfoChanging(value);
                this.ReportPropertyChanging("moreInfo");
                this._moreInfo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("moreInfo");
                this.OnmoreInfoChanged();
            }
        }
        private string _moreInfo;
        partial void OnmoreInfoChanging(string value);
        partial void OnmoreInfoChanged();
        /// <summary>
        /// There are no comments for Property avatar in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] avatar
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._avatar);
            }
            set
            {
                this.OnavatarChanging(value);
                this.ReportPropertyChanging("avatar");
                this._avatar = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("avatar");
                this.OnavatarChanged();
            }
        }
        private byte[] _avatar;
        partial void OnavatarChanging(byte[] value);
        partial void OnavatarChanged();
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_Categories_Users", "Categories")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Category> Categories
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Category>("GalleryModel.FK_Categories_Users", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Category>("GalleryModel.FK_Categories_Users", "Categories", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ImageComments in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_ImageComments_User", "ImageComments")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ImageComment> ImageComments
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ImageComment>("GalleryModel.FK_ImageComments_User", "ImageComments");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ImageComment>("GalleryModel.FK_ImageComments_User", "ImageComments", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ImageRatings in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_ImageRatings_User", "ImageRatings")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ImageRating> ImageRatings
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ImageRating>("GalleryModel.FK_ImageRatings_User", "ImageRatings");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ImageRating>("GalleryModel.FK_ImageRatings_User", "ImageRatings", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Images in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_Images_User", "Images")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Image> Images
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Image>("GalleryModel.FK_Images_User", "Images");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Image>("GalleryModel.FK_Images_User", "Images", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ImageVisits in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GalleryModel", "FK_ImageVisits_User", "ImageVisits")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ImageVisit> ImageVisits
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ImageVisit>("GalleryModel.FK_ImageVisits_User", "ImageVisits");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ImageVisit>("GalleryModel.FK_ImageVisits_User", "ImageVisits", value);
                }
            }
        }
    }
}
